# Canal Instance Configuration: example

# Slave ID (Must be unique)
canal.instance.mysql.slaveId = 1234

# MySQL 地址
canal.instance.master.address = mysql-inner:3306
canal.instance.master.journal.name = 
canal.instance.master.position = 
canal.instance.master.timestamp = 

# MySQL 用户
canal.instance.dbUsername = canal
canal.instance.dbPassword = canal123
canal.instance.connectionCharset = UTF-8

# 过滤规则
canal.instance.filter.regex = inner_gateway.inner_request
canal.instance.filter.black.regex = 

# 投递到 Kafka 的 Topic
canal.mq.topic = inner_request_binlog
canal.mq.partitionHash = inner_gateway.inner_request:request_id