# Canal Outer 镜像 - 监听 outer_gateway.outer_response
FROM canal/canal-server:v1.1.7

# 复制配置文件
COPY canal.properties /home/admin/canal-server/conf/canal.properties
COPY instance.properties /home/admin/canal-server/conf/example/instance.properties
