# Canal Server Configuration

# 关键配置：模式设置为 Kafka
canal.serverMode = kafka

# Kafka 地址
kafka.bootstrap.servers = kafka:9092
kafka.acks = all
kafka.compression.type = none
kafka.batch.size = 16384
kafka.linger.ms = 1
kafka.max.request.size = 1048576
kafka.buffer.memory = 33554432
kafka.max.in.flight.requests.per.connection = 1
kafka.retries = 0

# 默认实例
canal.destinations = example
# 实例全局锁
canal.instance.global.spring.xml = classpath:spring/default-instance.xml
