# Canal Inner 镜像 - 监听 inner_gateway.inner_request
FROM canal/canal-server:v1.1.7

# 复制配置文件
COPY canal.properties /home/admin/canal-server/conf/canal.properties
COPY instance.properties /home/admin/canal-server/conf/example/instance.properties
